# settings.py

NUM_PARALLEL = 1
BASE_PORT = 8010
SLEEP_TIME = 0.2
FIRST_BROWSER_AGE = 60 * 30
KILL_SPACING_S = 60 * 30
MAX_PARALLEL_PROCESS = 20

REFRESH_INTERVAL = 61 # NOTE: seet these to increase or decrease cookie numbers
COOKIE_LIFETIME = 60 * 60
MAX_COOKIES = 1000

COOKIES_DIR_PREFIX = ".cloudflare_cookies_"
BROWSER_PORTS_FILE = "~/browser_ports.json"
VERBOSE = False

# Optionally, if you want to group them (not necessary, but for completeness):
CLI_SETTINGS = {
    "NUM_PARALLEL": NUM_PARALLEL,
    "BASE_PORT": BASE_PORT,
    "SLEEP_TIME": SLEEP_TIME,
    "FIRST_BROWSER_AGE": FIRST_BROWSER_AGE,
    "KILL_SPACING_S": KILL_SPACING_S,
    "MAX_PARALLEL_PROCESS": MAX_PARALLEL_PROCESS,
}

CLOUDFLARE_COOKIE_MANAGER_SETTINGS = {
    "REFRESH_INTERVAL": REFRESH_INTERVAL,
    "COOKIE_LIFETIME": COOKIE_LIFETIME,
    "MAX_COOKIES": MAX_COOKIES,
    "COOKIES_DIR_PREFIX": COOKIES_DIR_PREFIX,
    "BROWSER_PORTS_FILE": BROWSER_PORTS_FILE,
    "VERBOSE": VERBOSE,
}
